apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kogito.knative.dev/release: v1.1.0
    role: kogito-source-webhook
  name: kogito-source-webhook
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    role: kogito-source-webhook
status:
  loadBalancer: {}
