/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-kogito/pkg/apis/kogito/v1alpha1"
)

// FakeKogitoSources implements KogitoSourceInterface
type FakeKogitoSources struct {
	Fake *FakeKogitoV1alpha1
	ns   string
}

var kogitosourcesResource = schema.GroupVersionResource{Group: "kogito.knative.dev", Version: "v1alpha1", Resource: "kogitosources"}

var kogitosourcesKind = schema.GroupVersionKind{Group: "kogito.knative.dev", Version: "v1alpha1", Kind: "KogitoSource"}

// Get takes name of the kogitoSource, and returns the corresponding kogitoSource object, and an error if there is any.
func (c *FakeKogitoSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KogitoSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kogitosourcesResource, c.ns, name), &v1alpha1.KogitoSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KogitoSource), err
}

// List takes label and field selectors, and returns the list of KogitoSources that match those selectors.
func (c *FakeKogitoSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KogitoSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kogitosourcesResource, kogitosourcesKind, c.ns, opts), &v1alpha1.KogitoSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KogitoSourceList{ListMeta: obj.(*v1alpha1.KogitoSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.KogitoSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kogitoSources.
func (c *FakeKogitoSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kogitosourcesResource, c.ns, opts))

}

// Create takes the representation of a kogitoSource and creates it.  Returns the server's representation of the kogitoSource, and an error, if there is any.
func (c *FakeKogitoSources) Create(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.CreateOptions) (result *v1alpha1.KogitoSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kogitosourcesResource, c.ns, kogitoSource), &v1alpha1.KogitoSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KogitoSource), err
}

// Update takes the representation of a kogitoSource and updates it. Returns the server's representation of the kogitoSource, and an error, if there is any.
func (c *FakeKogitoSources) Update(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (result *v1alpha1.KogitoSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kogitosourcesResource, c.ns, kogitoSource), &v1alpha1.KogitoSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KogitoSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKogitoSources) UpdateStatus(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (*v1alpha1.KogitoSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kogitosourcesResource, "status", c.ns, kogitoSource), &v1alpha1.KogitoSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KogitoSource), err
}

// Delete takes name of the kogitoSource and deletes it. Returns an error if one occurs.
func (c *FakeKogitoSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kogitosourcesResource, c.ns, name), &v1alpha1.KogitoSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKogitoSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kogitosourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KogitoSourceList{})
	return err
}

// Patch applies the patch and returns the patched kogitoSource.
func (c *FakeKogitoSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KogitoSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kogitosourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KogitoSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KogitoSource), err
}
