apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: event-display
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: kogito-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
