/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-kogito/pkg/apis/kogito/v1alpha1"
	scheme "knative.dev/eventing-kogito/pkg/client/clientset/versioned/scheme"
)

// KogitoSourcesGetter has a method to return a KogitoSourceInterface.
// A group's client should implement this interface.
type KogitoSourcesGetter interface {
	KogitoSources(namespace string) KogitoSourceInterface
}

// KogitoSourceInterface has methods to work with KogitoSource resources.
type KogitoSourceInterface interface {
	Create(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.CreateOptions) (*v1alpha1.KogitoSource, error)
	Update(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (*v1alpha1.KogitoSource, error)
	UpdateStatus(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (*v1alpha1.KogitoSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KogitoSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KogitoSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KogitoSource, err error)
	KogitoSourceExpansion
}

// kogitoSources implements KogitoSourceInterface
type kogitoSources struct {
	client rest.Interface
	ns     string
}

// newKogitoSources returns a KogitoSources
func newKogitoSources(c *KogitoV1alpha1Client, namespace string) *kogitoSources {
	return &kogitoSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kogitoSource, and returns the corresponding kogitoSource object, and an error if there is any.
func (c *kogitoSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KogitoSource, err error) {
	result = &v1alpha1.KogitoSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kogitosources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KogitoSources that match those selectors.
func (c *kogitoSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KogitoSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KogitoSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kogitosources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kogitoSources.
func (c *kogitoSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kogitosources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kogitoSource and creates it.  Returns the server's representation of the kogitoSource, and an error, if there is any.
func (c *kogitoSources) Create(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.CreateOptions) (result *v1alpha1.KogitoSource, err error) {
	result = &v1alpha1.KogitoSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kogitosources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kogitoSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kogitoSource and updates it. Returns the server's representation of the kogitoSource, and an error, if there is any.
func (c *kogitoSources) Update(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (result *v1alpha1.KogitoSource, err error) {
	result = &v1alpha1.KogitoSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kogitosources").
		Name(kogitoSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kogitoSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kogitoSources) UpdateStatus(ctx context.Context, kogitoSource *v1alpha1.KogitoSource, opts v1.UpdateOptions) (result *v1alpha1.KogitoSource, err error) {
	result = &v1alpha1.KogitoSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kogitosources").
		Name(kogitoSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kogitoSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kogitoSource and deletes it. Returns an error if one occurs.
func (c *kogitoSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kogitosources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kogitoSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kogitosources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kogitoSource.
func (c *kogitoSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KogitoSource, err error) {
	result = &v1alpha1.KogitoSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kogitosources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
