apiVersion: kogito.knative.dev/v1alpha1
kind: KogitoSource
metadata:
  name: my-kogito-source
spec:
  ## Target deployed Kogito service. In this example we use Knative Service, but can be any kind of "Podspecable" interface.
  ## see: https://knative.dev/docs/developer/concepts/duck-typing/ (Podspecable)
  subject:
    apiVesion: serving.knative.dev/v1
    kind: Service
    name: my-kogito-service
  # see sinks directory. use inmemory-channel.yaml to create the sink (or you can change it to any other sink you wish)
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: kogito-channel
