# see sinks directory. use inmemory-channel.yaml to create the sink (or you can change it to any other sink you wish)
apiVersion: kogito.knative.dev/v1alpha1
kind: KogitoSource
metadata:
  name: kogito-order-processing
spec:
  subject:
    apiVesion: serving.knative.dev/v1
    kind: Service
    name: kogito-order-processing
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: kogito-channel
